import { RoutesData } from "../types/helper.types";

export const allRoutes: RoutesData[] = [
  {
    id: "ownerDashboard",
    title: "Dashboard",
    icon: "home",
    path: "owner/index",
    iconType: "Feather",
    role: ["owner"],
  },
  {
    id: "ownerOrganizations",
    title: "Tashkilotlar",
    icon: "organization",
    path: "owner/organizations",
    iconType: "Octicons",
    role: ["owner"],
  },

  // consumers
  {
    id: "consumerDashboard",
    title: "Bosh sahifa",
    icon: "dashboard",
    path: "consumer/index",
    iconType: "MaterialIcons",
    role: ["consumer"],
  },
  {
    id: "consumerStatistics",
    title: "Statistika",
    icon: "pie-chart",
    path: "consumer/statistics",
    iconType: "SimpleLineIcons",
    role: ["consumer"],
  },
  {
    id: "consumerHistory",
    title: "Tarix",
    icon: "history",
    path: "consumer/history",
    iconType: "AntDesign",
    role: ["consumer"],
  },
  {
    id: "profile",
    title: "profile",
    icon: "user",
    path: "public/profile",
    iconType: "FontAwesome",
    role: ["consumer"],
  },
  {
    id: "organizationDashboard",
    title: "Bosh sahifa",
    icon: "space-dashboard",
    path: "organization/index",
    iconType: "MaterialIcons",
    role: ["organization"],
  },
  {
    id: "organizationConsumers",
    title: "Istemolchilar",
    icon: "users",
    path: "organization/consumers",
    iconType: "FontAwesome",
    role: ["organization"],
  },
  {
    id: "organizationMeters",
    title: "Hisoblagichlar",
    icon: "gas-meter",
    path: "organization/meters",
    iconType: "MaterialIcons",
    role: ["organization"],
  },
  {
    id: "organizationFinance",
    title: "Hisob kitob",
    icon: "wallet-outline",
    path: "organization/finance",
    iconType: "Ionicons",
    role: ["organization"],
  },
  {
    id: "organizationEmployees",
    title: "Hodimlar",
    icon: "users-cog",
    path: "organization/employees",
    iconType: "FontAwesome5",
    role: ["organization"],
  },
  // public
  // {
  //   id: "8"
  //   title: "Bildirishnomalar",
  //   icon: "notifications-sharp",
  //   path: "public/notification",
  //   iconType: "Ionicons",
  //   role: ["owner", "consumer", "organization"],
  // },
  // {
  //   id: "7",
  //   title: "profile",
  //   icon: "user",
  //   path: "public/profile",
  //   iconType: "FontAwesome",
  //   role: ["owner", "consumer", "organization"],
  // },
];
